### ISSUE TITLE
Railway (One-click deployment) not working

### ISSUE THREAD

**Issue by edubrigham** [n4ze3m/dialoqbase#287]
Hello,

I have tried using the Railway (One-click deployment) but it is not working. After successful deployment I get  a "Application failed to respond. This error appears to be caused by the application" error message.

<img width="1269" alt="Screenshot 2024-08-06 at 12 18 11" src="https://github.com/user-attachments/assets/919ec184-bd68-4f9b-86e7-0774575e7efc">

<img width="1027" alt="Screenshot 2024-08-06 at 12 29 49" src="https://github.com/user-attachments/assets/9a9bcb77-73ec-4f55-b185-4161937d6dbc">

<img width="872" alt="Screenshot 2024-08-06 at 12 18 59" src="https://github.com/user-attachments/assets/bc771f43-7fe9-4372-93ba-ff59414e8602">

**Comment by n4ze3m** [comment]
Hey @edubrigham, This error occurred due to Railway's new runtime. Please try the following steps:

1. Go to Dialogbase settings in Railway.
2. Scroll down until you see the runtime section and change it to `legacy`.
3. Deploy.
4. Go to the same settings, delete the generated domain, regenerate a new one, and deploy again.

This should hopefully work.

**Comment by edubrigham** [comment]
> Hey @edubrigham, This error occurred due to Railway's new runtime. Please try the following steps:
> 
> 1. Go to Dialogbase settings in Railway.
> 2. Scroll down until you see the runtime section and change it to `legacy`.
> 3. Deploy.
> 4. Go to the same settings, delete the generated domain, regenerate a new one, and deploy again.
> 
> This should hopefully work.

Thank you! It works perfectly!

**Comment by rossman22590** [comment]
having this issue now lol

**Comment by rossman22590** [comment]
any other ideas to solve?
