### ISSUE TITLE
Railway template not working

### ISSUE THREAD

**Issue by elr9** [n4ze3m/dialoqbase#53]
The railway template keeps crashing with this error message:

﻿Error: Prisma schema validation - (get-config wasm)
﻿Error code: P1012
﻿error: Error validating datasource `db`: the URL must start with the protocol `postgresql://` or `postgres://`.
﻿-->  schema.prisma:8
﻿|
﻿7 |   provider   = "postgresql"
﻿8 |   url        = env("DATABASE_URL")
﻿|
﻿Validation Error Count: 1
﻿[Context: getConfig]
﻿Prisma CLI Version : 4.16.2
﻿error Command failed with exit code 1.

**Comment by n4ze3m** [comment]
Hey, sorry for the issue. I think it's because of a missing database URL. Can you watch this [video ](https://twitter.com/n4ze3m/status/1668208861663354882) or check the [documentation ](https://dialoqbase.n4ze3m.com/guide/self-hosting-railway.html) on how to obtain the Supabase URL? (railway's PostgreSQL doesn't support pgvector)

**Comment by elr9** [comment]
That was it, thank you very much! I greatly appreciate your super-quick response =)
